# Generated by Django 4.2.7 on 2024-02-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandas',
            name='artBnd',
        ),
        migrations.AddField(
            model_name='bandas',
            name='artBnd',
            field=models.ManyToManyField(help_text='Artistas da banda', null=True, related_name='elenco', to='vol1.artistas'),
        ),
    ]
