# Generated by Django 4.2.7 on 2024-02-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol1', '0002_remove_bandas_artbnd_bandas_artbnd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandas',
            name='artBnd',
            field=models.ManyToManyField(help_text='Artistas da banda', related_name='elenco', to='vol1.artistas'),
        ),
    ]
