# Generated by Django 4.2.7 on 2024-02-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol1', '0003_alter_bandas_artbnd'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentosMusicais',
            fields=[
                ('codIns', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nomIns', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'T000INS',
            },
        ),
    ]
