# Generated by Django 4.2.7 on 2024-02-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vol1', '0005_alter_artistas_insart'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerosMusicais',
            fields=[
                ('codGen', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nomGen', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'T000GEN',
            },
        ),
        migrations.AlterField(
            model_name='instrumentosmusicais',
            name='nomIns',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='bandas',
            name='genBnd',
            field=models.ForeignKey(blank=True, help_text='Gênero musical da banda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generos_musicais', to='vol1.generosmusicais'),
        ),
    ]
